# Enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable the Lily58 OLED Display
CONFIG_ZMK_DISPLAY=y

# Enable deep sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Enable experimental ble features
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
